name: Android build

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get

    - name: build APK
      shell: bash
      working-directory: ./example
      run: flutter build apk

    - name: build app bundle
      shell: bash
      working-directory: ./example
      run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64

    - name: Archive test results?
      uses: actions/upload-artifact@v2
      with:
          name: app-release-${{ github.sha }}.apk
          path: example/build/app/outputs/flutter-apk/app-release.apk

    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
          name: app-${{ github.sha }}.aab
          path: example/build/app/outputs/bundle/release/app.aab
